// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// pico_encoder //
// ------------ //

#define pico_encoder_wrap_target 9
#define pico_encoder_wrap 14

static const uint16_t pico_encoder_program_instructions[] = {
    0x4020, //  0: in     x, 32                      
    0x4040, //  1: in     y, 32                      
    0x60c2, //  2: out    isr, 2                     
    0x4002, //  3: in     pins, 2                    
    0xa0ee, //  4: mov    osr, !isr                  
    0xa0a7, //  5: mov    pc, osr                    
    0x0087, //  6: jmp    y--, 7                     
    0xe021, //  7: set    x, 1                       
    0xa031, //  8: mov    x, ::x                     
            //     .wrap_target
    0x004a, //  9: jmp    x--, 10                    
    0xa0ad, // 10: mov    pc, !status                
    0xa04a, // 11: mov    y, !y                      
    0x008d, // 12: jmp    y--, 13                    
    0xa04a, // 13: mov    y, !y                      
    0xe020, // 14: set    x, 0                       
            //     .wrap
    0x0002, // 15: jmp    2                          
    0x000f, // 16: jmp    15                         
    0x000b, // 17: jmp    11                         
    0x0106, // 18: jmp    6                      [1] 
    0x0409, // 19: jmp    9                      [4] 
    0x0106, // 20: jmp    6                      [1] 
    0x000f, // 21: jmp    15                         
    0x0409, // 22: jmp    9                      [4] 
    0x000b, // 23: jmp    11                         
    0x000b, // 24: jmp    11                         
    0x0409, // 25: jmp    9                      [4] 
    0x000f, // 26: jmp    15                         
    0x0106, // 27: jmp    6                      [1] 
    0x0409, // 28: jmp    9                      [4] 
    0x0106, // 29: jmp    6                      [1] 
    0x000b, // 30: jmp    11                         
    0x0102, // 31: jmp    2                      [1] 
};

#if !PICO_NO_HARDWARE
static const struct pio_program pico_encoder_program = {
    .instructions = pico_encoder_program_instructions,
    .length = 32,
    .origin = 0,
};

static inline pio_sm_config pico_encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pico_encoder_wrap_target, offset + pico_encoder_wrap);
    return c;
}

#endif
